### ISSUE TITLE
Exception has occurred: RuntimeError Bad password for File

### ISSUE THREAD

**Issue by ghost** [Ghostish/python-rar-cracker#2]

**Comment by Ghostish** [comment]
Sorry for the late response. But the error message you give is too short to contain any useful information. Maybe it's something related to your file path but I am not sure.

**Comment by mrinal-del** [comment]
while running the code  iam getting runfile('C:/Users/MRINAL/.spyder-py3/untitled0.py', wdir='C:/Users/MRINAL/.spyder-py3')
  File "C:\Users\MRINAL\anaconda3\lib\site-packages\brute.py", line 68
    product(
    ^
SyntaxError: Generator expression must be parenthesized

**Comment by antarxis** [comment]
> while running the code iam getting runfile('C:/Users/MRINAL/.spyder-py3/untitled0.py', wdir='C:/Users/MRINAL/.spyder-py3') File "C:\Users\MRINAL\anaconda3\lib\site-packages\brute.py", line 68 product( ^ SyntaxError: Generator expression must be parenthesized

same here
